# Generated by Django 4.0.2 on 2022-02-15 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
