# Generated by Django 4.0.2 on 2022-03-09 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunapp', '0002_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='location',
            field=models.CharField(choices=[('Difficult Run, Virginia', 'Difficult Run, Virginia'), ('Reston', 'Reston')], default='Reston', max_length=40),
        ),
    ]
